services:
  websocket-server:
    build: ./websocket-server
    env_file: 
      - ./.env
    environment:
      - PORT=${WEBSOCKET_PORT:-8081}
      - WEBSOCKET_HOST=0.0.0.0
      - EXTERNAL_URL=${PUBLIC_URL:-https://realtime.sandbox.rauda.ai}
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${WEBSOCKET_PORT:-8081}/public-url"]
      interval: 10s
      timeout: 5s
      retries: 5

  webapp:
    build:
      context: ./webapp
      args:
        - WEBSOCKET_SERVER_URL=http://websocket-server:${WEBSOCKET_PORT:-8081}
        - NEXT_PUBLIC_WEBSOCKET_SERVER_URL=${PUBLIC_URL:-https://realtime.sandbox.rauda.ai}
    env_file:
      - ./.env
    environment:
      - PORT=${WEBAPP_PORT:-3000}
      - NEXT_PRIVATE_WEBSOCKET_SERVER_URL=http://websocket-server:${WEBSOCKET_PORT:-8081}
      - NEXT_PUBLIC_WEBSOCKET_SERVER_URL=${PUBLIC_URL:-https://realtime.sandbox.rauda.ai}
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${WEBAPP_PORT:-3000}"]
      interval: 10s
      timeout: 5s
      retries: 5

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network
    depends_on:
      webapp:
        condition: service_healthy
      websocket-server:
        condition: service_healthy

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
